language: cpp
dist: trusty

addons:
  apt:
    packages:
    - realpath
    - build-essential

before_install:
- rm -rf $HOME/.cache/bazel/_bazel_$USER/install
- wget https://github.com/bazelbuild/bazel/releases/download/0.14.1/bazel-0.14.1-installer-linux-x86_64.sh
- chmod +x bazel-0.14.1-installer-linux-x86_64.sh
- ./bazel-0.14.1-installer-linux-x86_64.sh --user
- export PATH=$HOME/bin:$PATH
- which gcc

install:
- find / # this is ugly, but I will find where is cc1
  #- echo 'build --jobs=4 --curses=no --verbose_failures' >> $HOME/.bazelrc
  #- echo "import %workspace%/tools/bazelrc/linux-$CC" >> $HOME/.bazelrc

script: bazel build @haskell_clock//:clock -s --sandbox_debug

git:
  depth: 1
